version: 2
jobs:
  ios:
    macos:
      xcode: "10.0.0"
    working_directory: ~/react-native-webrtc-kit/
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          command: yarn global add react-native-cli
          working_directory: test/Touchstone
      - run:
          command: yarn install
          working_directory: test/Touchstone
      - run:
          command: rm -rf node_modules/react-native-webrtc-kit
          working_directory: test/Touchstone
      - run:
          command: git clone ../../../react-native-webrtc-kit node_modules/react-native-webrtc-kit
          working_directory: test/Touchstone
      - run:
          command: react-native link
          working_directory: test/Touchstone
      - run:
          command: pod install
          working_directory: test/Touchstone/ios
  android:
    docker:
      - image: circleci/android:api-23-node
    working_directory: ~/react-native-webrtc-kit/
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          command: yarn global add react-native-cli
          working_directory: test/Touchstone
      - run:
          command: yarn install
          working_directory: test/Touchstone
      - run:
          command: rm -rf node_modules/react-native-webrtc-kit
          working_directory: test/Touchstone
      - run:
          command: git clone ../../../react-native-webrtc-kit node_modules/react-native-webrtc-kit
          working_directory: test/Touchstone
      - run:
          command: react-native link
          working_directory: test/Touchstone


workflows:
  version: 2
  react-native:
    jobs:
      - ios:
          filters:
            branches:
              only:
                - master
                - develop
                - /feature\/.*/
      - android:
          filters:
            branches:
              only:
                - master
                - develop
                - /feature\/.*/
